version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:your_base64_encoded_key_here
    networks:
      - apinet
    command: sh -c "php artisan migrate && php -S 0.0.0.0:8000 -t public"
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - apinet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  apinet:
    driver: bridge